//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropShipToolsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayEnd
    {
        public int id { get; set; }
        public System.DateTime submit_dt { get; set; }
        public string submit_user { get; set; }
        public Nullable<System.DateTime> started_dt { get; set; }
        public Nullable<System.DateTime> completed_dt { get; set; }
    }
}
