//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropShipToolsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUI_POImport
    {
        public string Company { get; set; }
        public string PO_ { get; set; }
        public string VendorID { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string Status { get; set; }
        public string PUOM { get; set; }
        public string Buyer { get; set; }
        public long id { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
