//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropShipToolsData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WMS2Entities : DbContext
    {
        public WMS2Entities()
            : base("name=WMS2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DayEnd> DayEnds { get; set; }
    
        public virtual int usp_EOD_Shipments_Update()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EOD_Shipments_Update");
        }
    }
}
